---
- hosts: mesos
  roles:
    - mesos-common

- hosts: mesos_masters
  roles:
    - mesos-master
    - marathon
    - chronos

- hosts: mesos_minions
  roles:
    - mesos-minion

- hosts: mesos_lbs
  roles:
    - mesos-lb
